In [134]:
import pandas as pd
import numpy as np

Question # 1 - Read csv file and replace dashes with 0

In [148]:
#Since the column names are in first row, added header command to set first row as column names or header
#Replaced dashes with 0 with replace command. 
#printig first 15 rows with head command for data verifiction 

LaLiga = pd.read_csv('Laliga.csv',header = 1).replace('-',0)
LaLiga.head(15)

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
0,1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,33,23,8,8,3,4,79,1929,1929,1
1,2,Barcelona,86,4262,2762,1581,573,608,5900,3114,25,25,12,12,4,6,83,1929,1929,1
2,3,Atletico Madrid,80,3442,2614,1241,598,775,4534,3309,10,8,16,9,7,6,56,1929,2002-03,1
3,4,Valencia,82,3386,2664,1187,616,861,4398,3469,6,6,10,11,10,7,50,1931-32,1987-88,1
4,5,Athletic Bilbao,86,3368,2762,1209,633,920,4631,3700,8,7,10,5,8,10,49,1929,1929,1
5,6,Sevilla,73,2819,2408,990,531,887,3680,3373,1,4,4,5,12,6,32,1934-35,2001-02,1
6,7,Espanyol,82,2792,2626,948,608,1070,3609,3889,0,0,4,5,2,5,16,1929,1994-95,3
7,8,Real Sociedad,70,2573,2302,864,577,861,3228,3230,2,3,2,5,4,3,19,1929,2010-11,1
8,9,Zaragoza,58,2109,1986,698,522,766,2683,2847,0,1,4,5,4,4,18,1939-40,2012-13,2
9,10,Real Betis,51,1884,1728,606,440,682,2159,2492,1,0,2,3,4,4,14,1932-33,2015-16,1
10,11,Deportivo La Coruna,45,1814,1530,563,392,575,2052,2188,1,5,4,1,0,1,12,1941-42,2014-15,1
11,12,Celta Vigo,51,1789,1698,586,389,723,2278,2624,0,0,0,2,4,5,11,1939-40,2012-13,4
12,13,Valladolid,42,1471,1466,463,384,619,1767,2180,0,0,0,1,1,1,3,1948-49,2013-14,4
13,14,Racing Santander,44,1416,1428,453,336,639,1843,2368,0,1,1,2,0,1,5,1929,2011-12,2
14,15,Sporting Gijon,43,1389,1458,471,358,629,1753,2152,0,1,1,2,2,1,7,1944-45,2015-16,2

Question # 2 Print all the teams which have started playing between 1930-1980. (5 points)

In [186]:
#Method -1
#Sliced the Debut column and applied lambda function
#Printed both Team name Debut column value 
#Sorted the result by Debut year for easy verification 

LaLiga[LaLiga.Debut.str.slice(0,4).astype(int).apply(lambda x: x> 1929 and x <1981)][["Team","Debut"]].sort_values('Debut')

                   Team    Debut
28               Alaves  1930-31
3              Valencia  1931-32
9            Real Betis  1932-33
17               Oviedo  1933-34
5               Sevilla  1934-35
25             Hercules  1935-36
15              Osasuna  1935-36
8              Zaragoza  1939-40
11           Celta Vigo  1939-40
27               Murcia  1940-41
21              Granada  1941-42
10  Deportivo La Coruna  1941-42
34            Castellon  1941-42
31             Sabadell  1943-44
14       Sporting Gijon  1944-45
49             Alcoyano  1945-46
46            Gimnastic  1947-48
12           Valladolid  1948-49
16               Malaga  1949-50
54               Lleida  1950-51
19           Las Palmas  1951-52
58      Atletico Tetuan  1951-52
50                 Jaen  1953-54
59     Cultural Leonesa  1955-56
57               Condal  1956-57
23                Elche  1959-60
18             Mallorca  1960-61
26             Tenerife  1961-62
37              Cordoba  1962-63
29              Levante  1963-64
41           Pontevedra  1963-64
40            Burgos CF  1971-72
30            Salamanca  1974-75
22       Rayo Vallecano  1977-78
32                Cadiz  1977-78
39           Recreativo  1978-79
52           AD Almeria  1979-80

In [187]:
#Method - 2
Debut_Year = LaLiga["Debut"].str[0:4].astype(int)
LaLiga[(Debut_Year > 1929) & (Debut_Year < 1981)][['Team','Debut']].sort_values('Debut')

                   Team    Debut
28               Alaves  1930-31
3              Valencia  1931-32
9            Real Betis  1932-33
17               Oviedo  1933-34
5               Sevilla  1934-35
25             Hercules  1935-36
15              Osasuna  1935-36
8              Zaragoza  1939-40
11           Celta Vigo  1939-40
27               Murcia  1940-41
21              Granada  1941-42
10  Deportivo La Coruna  1941-42
34            Castellon  1941-42
31             Sabadell  1943-44
14       Sporting Gijon  1944-45
49             Alcoyano  1945-46
46            Gimnastic  1947-48
12           Valladolid  1948-49
16               Malaga  1949-50
54               Lleida  1950-51
19           Las Palmas  1951-52
58      Atletico Tetuan  1951-52
50                 Jaen  1953-54
59     Cultural Leonesa  1955-56
57               Condal  1956-57
23                Elche  1959-60
18             Mallorca  1960-61
26             Tenerife  1961-62
37              Cordoba  1962-63
29              Levante  1963-64
41           Pontevedra  1963-64
40            Burgos CF  1971-72
30            Salamanca  1974-75
22       Rayo Vallecano  1977-78
32                Cadiz  1977-78
39           Recreativo  1978-79
52           AD Almeria  1979-80

Question # 3 Print the list of teams which came Top 5 in terms of points

In [151]:
LaLiga['Points'] = pd.to_numeric(LaLiga['Points'])
LaLiga.sort_values('Points',ascending = False).head(5)[['Team','Points']]

              Team  Points
0      Real Madrid    4385
1        Barcelona    4262
2  Atletico Madrid    3442
3         Valencia    3386
4  Athletic Bilbao    3368

Question # 4 Write a function with name “Goal_diff_count” which should return all the teams with their Goal Differences. Using the same function, find the team which has maximum and minimum goal difference.

In [99]:
# Method - 1
def Goal_diff_count(GoalsFor, GoalsAgainst):
    return (GoalsFor - GoalsAgainst)

print('Team with max Goal Diff:',LaLiga.loc[Goal_diff_count((LaLiga['GoalsFor']).astype(int),LaLiga['GoalsAgainst'].astype(int)).idxmax()]['Team'])
print('Team with max Goal Diff:',LaLiga.loc[Goal_diff_count((LaLiga['GoalsFor']).astype(int),LaLiga['GoalsAgainst'].astype(int)).idxmin()]['Team'])

Team with max Goal Diff: Real Madrid
Team with max Goal Diff: Racing Santander

In [152]:
# Method - 2
# This is how we make life more complex

df1 = pd.DataFrame(columns=['Team','goal_diff'])

def Goal_diff_count(Team,GoalsFor, GoalsAgainst,row_index):
    goal_diff = int(GoalsFor) - int(GoalsAgainst)
    df1.loc[row_index] = [Team,goal_diff]

for row_index,row in LaLiga.iterrows():
    Goal_diff_count(row['Team'],row['GoalsFor'],row['GoalsAgainst'],row_index)
    
df1['goal_diff'] = pd.to_numeric(df1['goal_diff'])

print ('Team with max goal diff:',df1.loc[df1['goal_diff'].idxmax()]['Team'])
print ('Team with max goal diff:',df1.loc[df1['goal_diff'].idxmin()]['Team'])

Team with max goal diff: Real Madrid
Team with max goal diff: Racing Santander

Question # 5 Create a new column with name “Winning Percent” and append it to the data set (5 points)
Percentage of Winning = (GamesWon / GamesPlayed)*100

If there are any numerical error, replace it with 0%

Print the top 5 teams which has the highest Winning percentage

In [128]:
# Method 1 - using sort_values
LaLiga['Winning Percent'] = (LaLiga['GamesWon'].astype(int) / LaLiga['GamesPlayed'].astype(int))*100
LaLiga.fillna(0,inplace= True)
LaLiga.sort_values('Winning Percent',axis = 0 , ascending = False)[['Team','Winning Percent']].head(5)

              Team  Winning Percent
0      Real Madrid        59.630702
1        Barcelona        57.241130
2  Atletico Madrid        47.475134
3         Valencia        44.557057
4  Athletic Bilbao        43.772629

In [129]:
#Method 2 - using nlargest
LaLiga['Winning Percent'] = (LaLiga['GamesWon'].astype(int) / LaLiga['GamesPlayed'].astype(int))*100
LaLiga.fillna(0,inplace= True)
LaLiga.nlargest(5,['Winning Percent'])[['Team','Winning Percent']]

              Team  Winning Percent
0      Real Madrid        59.630702
1        Barcelona        57.241130
2  Atletico Madrid        47.475134
3         Valencia        44.557057
4  Athletic Bilbao        43.772629

Question # 6 Group teams based on their “Best position” and print the sum of their points for all positions

In [194]:
#Method 1
LaLiga.groupby("BestPosition")["Points"].agg(['sum'])

                sum
BestPosition
1             27933
2              6904
3              5221
4              6563
5              1884
6              2113
7              1186
8              1134
9                96
10              450
11              445
12              511
14               71
15               14
16               81
17              266
19               81
20               34

In [200]:
# Method - 2
LaLiga.groupby("BestPosition").agg({"Points":[('Total Points ','sum')]})

                    Points
             Total Points
BestPosition
1                    27933
2                     6904
3                     5221
4                     6563
5                     1884
6                     2113
7                     1186
8                     1134
9                       96
10                     450
11                     445
12                     511
14                      71
15                      14
16                      81
17                     266
19                      81
20                      34